<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\Icode\NovaPasta\**" />
    <EmbeddedResource Remove="Interfaces\Icode\NovaPasta\**" />
    <None Remove="Interfaces\Icode\NovaPasta\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dojinho.Data\Dojinho.Data.csproj" />
    <ProjectReference Include="..\Dojinho.Domain\Dojinho.Domain.csproj" />
  </ItemGroup>

</Project>
